chore(deps): renovate 2025-04-17
chore(deps): update terraform proxmox to v0.76.0 (#268)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update helm release argo-cd to v7.8.26 (#269)

* chore(deps): update terraform proxmox to v0.76.0 (#268)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* fix(tofu): volume-provisioning

A Proxmox update probably broke/changed the way API requests are handled, giving errors on UPDATE calls with parameters that aren't used

Error: unexpected response code '400': {"data":null,"errors":{"format":"property is not defined in schema and the schema does not allow additional properties","vmid":"property is not defined in schema and the schema does not allow additional properties","size":"property is not defined in schema and the schema does not allow additional properties","filename":"property is not defined in schema and the schema does not allow additional properties"}}

Also update Mastercard/restapi provider

* chore(deps): update helm release argo-cd to v7.8.26

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Vegard Hagen <vegard@stonegarden.dev>

chore(deps): update keycloak docker tag to v24.5.2 (#270)

* chore(deps): update terraform proxmox to v0.76.0 (#268)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* fix(tofu): volume-provisioning

A Proxmox update probably broke/changed the way API requests are handled, giving errors on UPDATE calls with parameters that aren't used

Error: unexpected response code '400': {"data":null,"errors":{"format":"property is not defined in schema and the schema does not allow additional properties","vmid":"property is not defined in schema and the schema does not allow additional properties","size":"property is not defined in schema and the schema does not allow additional properties","filename":"property is not defined in schema and the schema does not allow additional properties"}}

Also update Mastercard/restapi provider

* chore(deps): update keycloak docker tag to v24.5.2

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Vegard Hagen <vegard@stonegarden.dev>

chore(deps): update ghcr.io/prometheus-community/charts/kube-prometheus-stack docker tag to v70.7.0 (#271)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update sealed-secrets docker tag to v2.5.9 (#272)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update cloudflare/cloudflared docker tag to v2025.4.0 (#273)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update media containers (#274)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update netbird to v0.41.3 (#275)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update dependency corewire/images/crossplane/function-keycloak-builtin-objects to v3.0.1 (#277)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update cilium to v1.17.3 (#278)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update docker.io/adguard/adguardhome docker tag to v0.107.60 (#279)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

chore(deps): update helm release authelia to v0.10.5 (#280)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>